.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. tabit_qt test_tabit_qt
clean: FORCE
	$(MAKE) -C .. tabit_qt_clean test_tabit_qt_clean
check: FORCE
	$(MAKE) -C .. test_tabit_qt_check
tabit-qt tabit-qt.exe: FORCE
	 $(MAKE) -C .. tabit_qt
